In [2]:
#numpy import
import numpy as np

In [3]:
#creating numpy arrays from a python list
my_list = [1,2,3]
my_list


[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
#create a matrix
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#build in methods 
#arange
np.arange(0,10)

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
#Zeros and Ones
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((4))

array([1., 1., 1., 1.])

In [11]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.full((4,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
#linspace
[return evaly spaced number over a specified interval]
np.linspace[1,10,0.5]

In [17]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
np.linspace(2,10,50)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [12]:
np.linspace(0,10,2)

array([ 0., 10.])

In [13]:
np.linspace(0,10,60)

array([ 0.        ,  0.16949153,  0.33898305,  0.50847458,  0.6779661 ,
        0.84745763,  1.01694915,  1.18644068,  1.3559322 ,  1.52542373,
        1.69491525,  1.86440678,  2.03389831,  2.20338983,  2.37288136,
        2.54237288,  2.71186441,  2.88135593,  3.05084746,  3.22033898,
        3.38983051,  3.55932203,  3.72881356,  3.89830508,  4.06779661,
        4.23728814,  4.40677966,  4.57627119,  4.74576271,  4.91525424,
        5.08474576,  5.25423729,  5.42372881,  5.59322034,  5.76271186,
        5.93220339,  6.10169492,  6.27118644,  6.44067797,  6.61016949,
        6.77966102,  6.94915254,  7.11864407,  7.28813559,  7.45762712,
        7.62711864,  7.79661017,  7.96610169,  8.13559322,  8.30508475,
        8.47457627,  8.6440678 ,  8.81355932,  8.98305085,  9.15254237,
        9.3220339 ,  9.49152542,  9.66101695,  9.83050847, 10.        ])

In [16]:
#eye
#[creates an identity matrix]
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#random
#numpy also has a lots ways to create random number arrays
#rand[Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)]
np.random.rand(5)

array([0.21568722, 0.4526816 , 0.69122108, 0.42308764, 0.0388831 ])

In [21]:
np.random.rand(5,5)

array([[0.6024094 , 0.51339741, 0.44847088, 0.60635037, 0.2485023 ],
       [0.47504633, 0.49133628, 0.4749471 , 0.04643222, 0.38193338],
       [0.05654464, 0.27565088, 0.85471859, 0.4426932 , 0.36726117],
       [0.09682109, 0.71948267, 0.29205402, 0.58525964, 0.64746972],
       [0.07864106, 0.40156709, 0.0846776 , 0.68805238, 0.93716843]])

In [22]:
#randn
np.random.randn(2)

array([ 1.31423723, -0.55442567])

In [23]:
np.random.randn(5,5)

array([[ 0.73340142, -0.97596701, -1.54253242,  0.31464539,  1.636635  ],
       [-0.23587036,  0.38836812, -0.10289155, -1.45205338,  0.404914  ],
       [ 1.06349259,  0.96250531, -0.2005097 , -0.4189794 , -1.19335965],
       [-0.53263155,  0.26908562,  0.12842814, -0.87271818,  0.27437172],
       [-0.35413923,  0.53886032,  1.14119294, -1.8743483 ,  0.2126771 ]])

In [24]:
#randint
np.random.randint(1,100)

64

In [25]:
np.random.randint(1,100)

39

In [26]:
np.random.randint(1,100,10)

array([80, 88, 60, 65, 46, 87, 62, 29, 30, 77])

In [27]:
#array attributes and methods
arr=np.arange(25)
nararr=np.random.randint(1,50,10)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
nararr

array([15, 40, 18, 43, 32, 23, 48, 41, 42,  1])

# reshape

In [30]:
#returns an array containg the same data with new shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [31]:
nararr

array([15, 40, 18, 43, 32, 23, 48, 41, 42,  1])

In [32]:
nararr.max()

48

In [33]:
nararr.min()

1

In [34]:
nararr.argmax()

6

In [35]:
nararr.argmin()

9

# shape

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.shape

(25,)

In [38]:
#notice the two sets of  brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
arr.reshape(1,25).shape

(1, 25)

In [40]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# Datatype

In [41]:
arr.dtype

dtype('int32')

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# array dimensional check

In [45]:
arr.ndim

1

In [46]:
arr.size

25

In [47]:
arr.itemsize

4

# Indexing,Slicing,Iterating

In [48]:
a=np.arange(10)**3

In [49]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [50]:
a[2]

8

In [51]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [52]:
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [54]:
#iterating
for row in arr:
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
